### PR TITLE
~ Extract localizable strings for sidebar, settings, about, start, tap & maintenance

### PR DESCRIPTION
**Pull request by sebj**
**Background**
Extract strings from views into a `Localizable.strings` file and a `Localizable.stringsdict` plist-formatted file for plurals.
This covers: sidebar, settings, about, start, add tap, tap details, and maintenance.

I probably should have split this work up earlier to get your feedback on the general format of localization keys. 😅  Still quite a few more views left to go, which will land in a separate PR if you're happy with this format!

**Changes**
* Views now reference a localisation key like `maintenance.title` rather than than an actual string
* Custom views that took a `String` to display `Text` now take a `LocalizedStringKey` instead
* The only change to copy has been replacing `...` (3 full stops) with `…` (Unicode horizontal ellipsis), everything else is untouched

### CODE REVIEW

**Comment by buresdv** [comment]
I think this is pretty good! I take it that you tested that everything works as it should, right?

If it all works fine, you can push the rest of the views into this PR and I'll merge it all at once.

**Comment by sebj** [comment]
> I take it that you tested that everything works as it should, right?

Yep, all working well so far!

> you can push the rest of the views into this PR and I'll merge it all at once

Cool, will do in that case!

**Comment by sebj** [comment]
All done, good for a final review!

**Comment by sebj** [comment]
All done, ready for review!

**Comment by buresdv** [comment]
Looks good! I'll merge it into its own branch and click through, and then merge the branch later :)

If you know any other language, you can also have a go at translating it 😄 I will translate it into all the languages I know.

**Pull request merged**
