### PR TITLE
+ Start screen icons

### PR DESCRIPTION
**Pull request by sebj**
Add icons to each item on the start screen, and slightly increase padding to let each item 'breathe' a bit.

Screenshot 2023-03-11 at 14 13 45

### CODE REVIEW

**Comment by buresdv** [comment]
Could you just make the image in `GroupBoxHeadlineGroup` optional? We might use it without any pictures somewhere

**Comment by sebj** [comment]
Sure thing, changed!

**Comment by buresdv** [comment]
Thank you very much!

**Review by buresdv — APPROVED** [review]
Looks good

**Pull request merged**
