### PR TITLE
Update Simplified & Traditional Chinese localization

### PR DESCRIPTION
**Pull request by Jerry23011**
### Changes
- Add Traditional Chinese localization for translator `about.translator.3.purpose" = "為 Cork 提供德語翻譯";`
- Add Simplified Chinese localization for translator `about.translator.3.purpose" = "为 Cork 提供了德语翻译";`
- Add new German locales

@sh95014 Could you check the TC translation if you have time 😄
@hecaex New German locales are ready 🚀

### CODE REVIEW

**Comment by hecaex** [comment]
Great adding more languages 💪

**Comment by hecaex** [comment]
See also [Pull Request #120](https://github.com/buresdv/Cork/pull/120)

**Comment by shuang886** [comment]
LGTM, thanks!

**Comment by sh95014** [comment]
LGTM, thanks!

**Pull request merged**
