### PR TITLE
Update Simplified Chinese localization

### PR DESCRIPTION
**Pull request by Jerry23011**
- Latest SC translations for `main`

### CODE REVIEW

**Review by buresdv — APPROVED** [review]
我欠你一条命，兄弟 🙇

**Comment by Jerry23011** [comment]
我的天😂
I'm so curious where you learned all these

**Comment by buresdv** [comment]
丹丘中文 on Douyin 😂 I've been working really hard on my Chinese lately, I got a lot of motivation 😬

**Comment by Jerry23011** [comment]
Amazing 😂

**Pull request merged**
