### PR TITLE
+ Request the sudo password

### PR DESCRIPTION
**Pull request by louchebem06**
I've created a small script that uses osascript to request the password, and when a brew command requires sudo, the script is invoked to provide it.

### CODE REVIEW

**Comment by buresdv** [comment]
Ooh that's an interesting solution.
1. Does this solve that "cannot run Homebrew as root" [problem](https://github.com/buresdv/Cork/issues/164#issuecomment-1749685939)?
2. Does it require password every time you install something? I think it would be the best if it only required it when the package needs it
3. I was thinking, if I saw a popup as a user, which is not the standard one for escalating privileges ([this one](https://i.imgur.com/qOFbrZP.png)), I'd not want to put my password in because I'd think someone is trying to steal it / hack me

**Comment by buresdv** [comment]
Thank you for the info! I'll merge it

**Comment by deinspanjer** [comment]
I'm wondering if when you merged this, you also ensured the SUDO_ASKPASS environment variable is pointing to the script is part of the environment of the task that is executing brew commands?

I am getting started with Cork and found that it is showing the sudo errors when trying to do an upgrade even though this askpass should have prompted me.

**Comment by buresdv** [comment]
I ended up not using this solution in the end (even though it's still merged to an existing branch) because there were a lot of issues with security concerns. So this technically isn't implemented in any Cork version, I'm just keeping it merged in that branch so I can come back to it if I figure anything out about this entire topic, or anyone who can help reaches out.

**Pull request merged**
