### PR TITLE
Add GitHub Action to run swiftlint, swift build, and swift test

### PR DESCRIPTION
**Pull request by cclauss**
Test results: https://github.com/cclauss/Cork/actions
* `swift build` and `swift test` would require a `Package.swift` file.

### CODE REVIEW

**Comment by buresdv** [comment]
I have very little experience with CI, could you please tell me more about what makes this useful? :)

**Comment by cclauss** [comment]
Each time someone changes code to this repository, a continuous integration test is run to build and then run the tests.  If their changes have broken the tests then we know that fixes should be made before merging those changes.  There is also a lint step to see if the code is properly formatted.

Looking at the usual test results should give you a better idea: https://github.com/cclauss/Cork/actions

**Comment by buresdv** [comment]
Thank you, is there a way to graphically report the results of this analysis? So we don't have to keep going into the run reports.

**Comment by cclauss** [comment]
>  is there a way to graphically report the results of this analysis

If you approve the workflow run then you will see the graphical results.

> a way to provide a custom Swiftlint configuration file?

https://github.com/realm/SwiftLint?tab=readme-ov-file#configuration documents how to add `.swiftlint.yml` to this repo.

**Comment by buresdv** [comment]
Alright, thanks a lot :)

**Pull request merged**
