### PR TITLE
update zh-Hant localization

### PR DESCRIPTION
**Pull request by sh95014**

### CODE REVIEW

**Comment by buresdv** [comment]
Thank you very much for the fast translation 😊

**Comment by buresdv** [comment]
I've added you to the list of translators, where would you like your "Go to profile" button profile to lead? :)

**Comment by sh95014** [comment]
“sh95014” and “https://github.com/sh95014” would be fine for now. Thanks!  :)

**Comment by buresdv** [comment]
Alright, I've added you :) 

Snímek obrazovky 2023-04-04 v 23 49 21

I'll ping you when I have more than one line to translate 😄

**Pull request merged**
